# Site settings
title: Mark Swedberg
email: contact@markswedberg.com
description: > # this means to ignore newlines until "baseurl:"
  Mark Swedberg is a UX/UI designer with seven years of industry
  experience, including startup incubators, government programs,
  and international teams. Learn more about his portfolio and
  work process here.
# url: "http://markswedberg.com" # the base hostname & protocol for your site
twitter_username: swedy13
github_username:  swedy13


# Outputting
permalink: /:categories/:title
# paginate_path: /page:num
timezone:      America/Chicago
# quiet:    false
# defaults: []


# Server
# detach:  false
# port:    4000
# host:    127.0.0.1
baseurl: "/" # the subpath of your site, e.g. /blog


# File Locations
# source:       .
# destination:  ./_site
# plugins_dir:  ./_plugins
# layouts_dir:  ./_layouts
# data_dir:     ./_data
# includes_dir: ./_includes
# collections:  null


# Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false


# Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      []
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Plugins
# whitelist: []
# gems:      []


# Conversion
markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
incremental: true


# Markdown Processors
